services:
  fruit-analyse-service:
    image: fruitsanalysis:latest
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models  # 挂载模型目录
      - ./app:/app/app  # 挂载应用代码目录
    environment:
      - PYTHONUNBUFFERED=1
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # 添加热挂载
    restart: unless-stopped
